import showcase from "./showcase.json" with { type: "json" };

export { showcase };

export const materials = [
  {
    id: "ivory",
    name: "山岚白",
    sub: "细腻乳胶漆",
    color: "#e6e5df",
    texture: "",
    type: "walls",
  },
  {
    id: "sage",
    name: "雾岛绿",
    sub: "哑光艺术漆",
    color: "#c7cec0",
    texture: "",
    type: "walls",
  },
  {
    id: "sand",
    name: "暖砂岩",
    sub: "天然石材",
    color: "#d1b594",
    texture: "stone",
    type: "walls",
  },
  {
    id: "oak",
    name: "自然橡木",
    sub: "实木纹理",
    color: "#ab7340",
    texture: "wood",
    type: "floor",
  },
  {
    id: "gray",
    name: "晨雾灰",
    sub: "微水泥",
    color: "#aebac2",
    texture: "stone",
    type: "walls",
  },
  {
    id: "cream",
    name: "奶油白",
    sub: "柔光饰面",
    color: "#edeee7",
    texture: "",
    type: "walls",
  },
  {
    id: "linen",
    name: "织云白",
    sub: "亚麻织物",
    color: "#d8d6c8",
    texture: "linen",
    type: "fabric",
  },
  {
    id: "rust",
    name: "陶土棕",
    sub: "温润肌理",
    color: "#b46b3f",
    texture: "",
    type: "walls",
  },
  {
    id: "walnut",
    name: "烟熏胡桃",
    sub: "天然木皮",
    color: "#785137",
    texture: "wood",
    type: "floor",
  },
  {
    id: "blue",
    name: "暮山蓝",
    sub: "哑光饰面",
    color: "#465969",
    texture: "",
    type: "walls",
  },
  {
    id: "gold",
    name: "麦穗黄",
    sub: "温暖色彩",
    color: "#cfa84d",
    texture: "",
    type: "walls",
  },
  {
    id: "honey",
    name: "蜂蜜橡木",
    sub: "实木纹理",
    color: "#d49c57",
    texture: "wood",
    type: "floor",
  },
  {
    id: "charcoal",
    name: "岩墨黑",
    sub: "深色饰面",
    color: "#303d46",
    texture: "",
    type: "walls",
  },
  {
    id: "teal",
    name: "远山青",
    sub: "棉麻织物",
    color: "#698b8d",
    texture: "linen",
    type: "fabric",
  },
  {
    id: "warm",
    name: "燕麦米",
    sub: "绒感织物",
    color: "#c4b497",
    texture: "linen",
    type: "fabric",
  },
];
export const presets = [
  {
    id: "midday",
    name: "白天",
    time: "12:00",
    icon: "sun",
    intensity: 3.0,
    color: "#fffaf1",
    position: [1, 12, 2],
    ambient: 1.1,
    exposure: 1.0,
  },
  {
    id: "night",
    name: "夜晚",
    time: "21:00",
    icon: "moon",
    intensity: 0.07,
    color: "#96c7ff",
    position: [6, 8, -3],
    ambient: 0.18,
    exposure: 0.9,
  },
];
